name = "NQ Order Pixel"
type = "web_pixel_extension"
handle = "nq-order-pixel"

runtime_context = "strict"

[customer_privacy]
  analytics = "disabled"
  preferences = "disabled"
  marketing = "disabled"
  sale_of_data = "disabled"