name = "NQ Order Pixel"
type = "web_pixel_extension"
handle = "nq-order-pixel"

runtime_context = "strict"

[customer_privacy]
  analytics = false
  preferences = false
  marketing = false
  sale_of_data = "disabled"

[settings]
  type = "object"